### ISSUE TITLE
Team - Content updates

### ISSUE THREAD

**Issue by reeceawalsh** [NewcastleRSE/sweet-project-website#13]
Client comments:

- [x] Staff job titles updated as per document
- [x] Some pictures are out of focus (asked Mark to request better photos)
- [x] Add in links to core team institutional pages (asked Mark to clarify whether each card should go to a specific staff members profile on brooks)
- [ ] Photos missing of Jan and Lesley – our PAG co-chair (asked Mark to request these)
- [ ] Move the following text from the PAG section ‘We also set up a Community of Interest, a group of 28 women who have previously had breast cancer and have been prescribed hormone therapy. They advise us on an ad hoc basis, via email, on a range of topics such as real-life hints and tips for dealing with side-effects, for inclusion on the HT&Me website’ to after the list of PAG members.
- [ ] The ‘Partners’ section is missing – this should appear under a heading of ‘Partners’ with the text of “We are working with the following organisations as partners” and then list the logos in the content doc in a more appropriate and equal size. 

Update: 

- Mark has already requested better images and the missing links.

**Comment by reeceawalsh** [comment]
Still haven't received images or more information. 
Added partners section to the footer, they can say if they want a specific section. 
They want the PAG information after the list of PAG members, which I haven't changed as it doesn't look right.

**Comment by KateCourt** [comment]
Closing as has been replaced by other issues
