### ISSUE TITLE
Identify and add icons for SWEET Programme page

### ISSUE THREAD

**Issue by KateCourt** [NewcastleRSE/sweet-project-website#48]
### What needs to be done?

- [ ] Research team to identify icons
- [ ] Kate to add them

**Comment by Thompsonse** [comment]
I've taken a look on HT&Me and the icons aren't really suitable think the icons that SJ put on the word document will be ok. 
Attached on document 
<img width="71" alt="Icon appointment" src="https://github.com/NewcastleRSE/sweet-project-website/assets/165272921/2e397133-2b3c-46ba-b271-f917777e6b4b">
<img width="131" alt="Icon HT Me" src="https://github.com/NewcastleRSE/sweet-project-website/assets/165272921/d2190fee-9201-4bf0-b320-d501881d5636">
<img width="82" alt="Icon Text or email message " src="https://github.com/NewcastleRSE/sweet-project-website/assets/165272921/cc1a1575-3689-40ec-bab8-67864c21a360">

**Comment by Thompsonse** [comment]
Hope the attached are ok?

**Comment by KateCourt** [comment]
Thanks @Thompsonse , I'll give these and go and you can see what you think. It'll be next week I get an opportunity to do this.

**Comment by Thompsonse** [comment]
Hi not sure if I can add these?

**Comment by KateCourt** [comment]
Sorry @Thompsonse I don't know why I closed this issue as I haven't implemented this. I will do!
