### ISSUE TITLE
PAG Photos

### ISSUE THREAD

**Issue by Thompsonse** [NewcastleRSE/sweet-project-website#49]
I was trying to add these myself however it came back with an error. 
I went onto the asset folder where i wanted to create another folder, then clicked new file, then added folder name/ didn't seems to like it. Be good to know how to do this for future. 
![Adrienne yellow hair](https://github.com/NewcastleRSE/sweet-project-website/assets/165272921/80bef789-63f8-4d82-b80d-3c02f53f1ebd)
![Akos 1](https://github.com/NewcastleRSE/sweet-project-website/assets/165272921/ca0935fd-f44b-485b-af17-129f9a1154d2)
![Helen](https://github.com/NewcastleRSE/sweet-project-website/assets/165272921/f8874d7e-175d-45c2-b31c-2935eeb8ee23)
![Jan B](https://github.com/NewcastleRSE/sweet-project-website/assets/165272921/4606344d-1a28-48cc-9d65-7c01c973e6c9)
![Jan Rose](https://github.com/NewcastleRSE/sweet-project-website/assets/165272921/e6b6b2c4-0f5b-4647-a871-395fc3d5b75b)
![Lesley](https://github.com/NewcastleRSE/sweet-project-website/assets/165272921/d8753dd9-abd2-414b-9e74-55120b28a7d9)
![Rosemary](https://github.com/NewcastleRSE/sweet-project-website/assets/165272921/17b7b44a-a6bc-4b74-89b8-6d6d94d152da)
![Sue B](https://github.com/NewcastleRSE/sweet-project-website/assets/165272921/b9a1d889-3604-4fa0-b59d-a89ced1c8ce3)
![Val jones](https://github.com/NewcastleRSE/sweet-project-website/assets/165272921/fc914d6e-3770-4f80-8956-8c99a560b0c2)
<img width="780" alt="Birgit" src="https://github.com/NewcastleRSE/sweet-project-website/assets/165272921/fafc5b4f-7dc6-4427-955c-180971cd48a5">

**Comment by KateCourt** [comment]
Hard to say why it didn't work without watching, but I've created a new folder 'pag' inside assets for you to use. The image urls need adding to 'data/patientAdvisory.yml' as you did with the other team photos. You'll see I've used on of the photos above for one of the chairs and a member just to act as demos.
