### ISSUE TITLE
SWEET Programme Page

### ISSUE THREAD

**Issue by Thompsonse** [NewcastleRSE/sweet-project-website#51]
Can the workstream text at the bottom be a larger font, bold and have colour, could use colour of the diagram for each workstream.

**Comment by KateCourt** [comment]
I've made them purple at the moment, as the colours in the diagram don't make for very readable text against a white background. Happy to change?

**Comment by Thompsonse** [comment]
Think that stands out better with the larger font. Only WS3 needs aligning
