### ISSUE TITLE
Embed recruitment animations on homepage and Taking part in SWEET section

### ISSUE THREAD

**Issue by Thompsonse** [NewcastleRSE/sweet-project-website#55]
Homepage
Put underneath SWEET is now recruiting from NHS sites across the UK.

Watch our recruitment animation here
https://vimeo.com/967809387?share=copy
https://vimeo.com/967812443?share=copy

Taking part in SWEET
Put underneath this section is for patients.
https://vimeo.com/967809387?share=copy
https://vimeo.com/967812443?share=copy

**Comment by Thompsonse** [comment]
Think the animation video will have to come off the homepage as it now only shows the women in the middle and a lot of her breast

**Comment by KateCourt** [comment]
We can remove the image completely if you'd prefer?

**Comment by Thompsonse** [comment]
The team definitely want to keep the image, it was perfect before i said put the amination on the front, tbh we only need the animation without subtitle on the homepage and keep both on the Taking part in SWEET

**Comment by KateCourt** [comment]
See what you think now?

**Comment by Thompsonse** [comment]
Looks much better, don't think we can do much about the women's breasts in the middle do feel sorry for the women on the left, literally left out

**Comment by KateCourt** [comment]
Heh yeah. She gets a look in on smaller screens at least!
