### ISSUE TITLE
Images to add - Pages- The SWEET Programme & Taking part in SWEET

### ISSUE THREAD

**Issue by Thompsonse** [NewcastleRSE/sweet-project-website#58]
To add an option so I can add an image to the top of the pages on The SWEET Programme & Taking Part in SWEET.
Have a few images however was wondering what the sizes need to be .

**Comment by KateCourt** [comment]
You can add images to 'assets/images' and add their url to '_data/images.yml' (replacing 'null' as in the demo). Images just need to be a high enough resolution that they aren't blurry. However, too large an image size and they will be slow to load. You probably won't run into this, but if you do, I can reduce the image resolution for you.

**Comment by KateCourt** [comment]
@Thompsonse the image filename should not have any spaces, I've made that change and you can see the image :)

**Comment by Thompsonse** [comment]
Thanks I'll make sure for the others there is no space.  If I want to add an image to the top of other pages like SWEET recruiting site & news & updates can i just add copy the format used for the other two pages?
Also I'm wondering if a colour can be added to the page border where the title is i.e Programme  as it looks very white.
See screenshots below
<img width="695" alt="Page border" src="https://github.com/NewcastleRSE/sweet-project-website/assets/165272921/e536bc3d-7d03-4ee9-99ee-235edca8ea5e">
or
<img width="695" alt="Page border with image" src="https://github.com/NewcastleRSE/sweet-project-website/assets/165272921/2fb156d5-121a-40fb-b37b-33d4fd7a7e87">

**Comment by KateCourt** [comment]
I'll need to update the code for other pages, I'll let you know once I've done that and you can go ahead and add images to any of the pages. I can do either a background colour or an image, which would you prefer? Personally, I think I prefer the image, although happy to do either!

**Comment by Thompsonse** [comment]
If you want to play around with any images for the pages I've put these in the asset folder
Women on beach to go on next to the title page SWEET Programme page
Mother & Daughter - Taking part 
HCP with tablet- Recruiting sites

**Comment by KateCourt** [comment]
Unfortunately, it's a little more manual to add images now they are in the heading. You no longer need to update the image url in the images.yml file. Instead, you need to provide me with the image name and the page it is for, and I'll update the code myself. I've done the images you provided (changing the image name to the page name just for convenience). I'll leave this issue open so you can add the details for further images here.
