### ISSUE TITLE
Matching header title to page titles

### ISSUE THREAD

**Issue by Thompsonse** [NewcastleRSE/sweet-project-website#61]
What section is this in to change the page titles to match the header titles for example News and updates is the header and the page title says updates.

**Comment by KateCourt** [comment]
I think I've changed them all now

**Comment by KateCourt** [comment]
I think I've changed them all now

**Comment by Thompsonse** [comment]
Thanks, I can see that they're in the ui folder i take it I can change these in the future myself

**Comment by KateCourt** [comment]
Sorry, I should have said where they are. They're in the `pages` folder in the corresponding html files. If you'd like to change the titles in the header, they're in `_data` in the yml files
