### ISSUE TITLE
Android device viewing

### ISSUE THREAD

**Issue by Thompsonse** [NewcastleRSE/sweet-project-website#63]
I've been told that when looking at the website on an android phone the pages look like they're in dark mode, not sure if this is a browser issue . It's fine on my iphone, the one thing i would say on my iphone the link comes up not secure.

**Comment by KateCourt** [comment]
It will follow whatever the phone is set to with regards to dark mode. For example, on my Android it appears with white background. I don't get the not secure message, could be iphones are a bit stricter than Android. The site has the required certificates and runs on https (secure) so I'm not sure why you're seeing this message.

**Comment by Thompsonse** [comment]
Thanks for the info
