### ISSUE TITLE
New corrected animation videos

### ISSUE THREAD

**Issue by Thompsonse** [NewcastleRSE/sweet-project-website#66]
The recruitment animation videos have been amended due to a small error. The new versions has been uploaded to vimeo.
Previously these were on the homepage and on the Taking part in SWEET section. (both versions) 
I can't seem to find the section to update the homepage link?
For the Taking part in SWEET is it just the iframe src vimeo links that need adding or do i have to script src
[coding.docx](https://github.com/user-attachments/files/16691733/coding.docx)

**Comment by KateCourt** [comment]
The home page code is in '_includes/hero.html' line 28.

You've found the correct bit of code to edit for both cases. The whole chunk from `<iframe ` onwards needs deleting and then you can paste in the one that vimeo provides. 

Let me know if you have any trouble.

**Comment by Thompsonse** [comment]
Thanks Kate, I'll give it a go. Just been told that I can't add the new videos yet as they have not been approved by ethic so I'll have to add the old videos back to vimeo arrrghh, this will be a new link so at least it will be practise for when i have to add the new versions

**Comment by KateCourt** [comment]
That's a drag, but yes, good chance to experiment!

**Comment by Thompsonse** [comment]
It seems to of worked my vimeo embed code was longer than the original code and it put your the style coding on the next line not sure if that matters, it looks ok though

**Comment by KateCourt** [comment]
Looks good! Yeah, with the HTML files, there's no problem about things going onto new lines or extra spaces going in.

**Comment by Thompsonse** [comment]
Thanks for checking Kate, very much appreciated, will just keep this ticket open just for info for me till I need to upload the revised versions in Sept.
