### ISSUE TITLE
Thermometer Goal or similar on website instead of recruitment numbers running along the top of banner.

### ISSUE THREAD

**Issue by Thompsonse** [NewcastleRSE/sweet-project-website#67]
It was suggested at a recent meeting that the recruitment versus target be shown as some type of visual feature i.e thermometer goal to replace the moving recruitment number running along the top of the banner.
I've had a look on a website called https://www.jlion.com/Tools/jTherm and they have the option to amend their example for free and it gives the html code
<img src="http://www.jlion.com/tools/Thermometer?

MIN=0&MAX=1460&VT=3&T=SWEET%20Recruitment&V=260&M=1&SC=0&CS=1&CI=en-GB&TH=0" style="border: solid 1px black;" alt="SWEET%20Recruitment" title="SWEET%20Recruitment" width="240" height="425"/> 

Would this be ok to add to replace the running total on the banner.
Have attached a file example of what it could look like.
![Thermometer goal](https://github.com/user-attachments/assets/1a6bc27c-e83c-47ab-be69-cd6d702ade6b)

If you can think of other features used on websites that would be better than a thermometer, I'm open to suggestions.

**Comment by KateCourt** [comment]
@Thompsonse nice find on the free thermometer code! I'm trying to think of something more relevant to the project, but googling it a lot of people do you a thermometer so perhaps we stick with that. Do you have thoughts where it would fit on the site? The home page is getting a bit full but it could go to the right of the welcome paragraph. I'd love to get rid of the white background but we'd have to create our own thermometer chart or look for a another library. See what you think - we can experiment with different locations on the site too

![Screenshot 2024-10-02 at 3 28 10 PM](https://github.com/user-attachments/assets/af743713-4fb4-4ac3-9831-793b3bb45fdd)

**Comment by Thompsonse** [comment]
Thanks for the visual , the front page is looking rather busy, not sure I like the welcome text that narrow although it could work. I'll show it to the team and get back to you. Yes shame about the white background, I might see if I can find a landscape measure as that would fit perfect on the white border where the running recruitment numbers are.

**Comment by KateCourt** [comment]
@Thompsonse Sure, and I'll have a look at javascript libraries I can use too

**Comment by Thompsonse** [comment]
Great yes think this would work on the border, is it easy to do a visual like you have above then I can show the team both options?
Target recruitment is 1460

**Comment by KateCourt** [comment]
![Screenshot 2024-10-03 at 10 49 17 AM](https://github.com/user-attachments/assets/3a1257f8-0802-4873-8e27-16535486a0cf)
I've simplified it down, I quite like it without the current total, but I can add that back in. What do you think?

**Comment by Thompsonse** [comment]
Looks great yes the team will want the recruitment total in.

**Comment by KateCourt** [comment]
![Screenshot 2024-10-03 at 11 09 47 AM](https://github.com/user-attachments/assets/61230fb8-f917-441e-a2e0-01386f45492a)


Something like this?

**Comment by Thompsonse** [comment]
Yes fab, I'll show these to the team and get back to you. 
Thanks again for your help

**Comment by Thompsonse** [comment]
Hi Kate,
Due to space on the front page, we've decided to keep the rolling text along the top and incorporate some extra wording which would include the target figure of 1460, e.g see below 
**We currently have 328 participants recruited to SWEET 22.47% (could round this up) of our 1460 target.** This wording may change so be good to know what sections it's placed under.
Also I'd have to keep amending this % when I amend the recruitment number on the header section.

**Comment by Thompsonse** [comment]
Hi Kate
Do you think what has been suggested above about amending the wording and adding a percentage will work?

**Comment by KateCourt** [comment]
To change the number and percentage, edit `_data/banner.yml`

**Comment by KateCourt** [comment]
`index.html`. - it's a bit of a hacky way of doing it, you'll see I've repeated the same phrase several times to fill the banner. It's not pretty code but it works! You can change this, or if there's some formatting changes you'd like, just let me know.

**Comment by Thompsonse** [comment]
Well if it works why waste time changing it. I'll just have to remember to change all the phrases.
Thanks for all your help.

**Comment by KateCourt** [comment]
Exactly! No problem, sorry you had to chase me up on it
