### ISSUE TITLE
Adding a section on the "SWEET recruiting sites" page called Breast Cancer Now Nurses

### ISSUE THREAD

**Issue by Thompsonse** [NewcastleRSE/sweet-project-website#68]
After the list of sites before the click here to view study documents.
Title- Breast Cancer Now Nurses
I have 3 nurses images and their profiles to add, 
Not sure if i can add a section?

**Comment by Thompsonse** [comment]
Hi Kate, I've got the profile images for the 3 Breast Cancer Now Nurses, I'll need a space to add some text underneath their image just like the Patient Advisory Group Members.

![Angela Vincent](https://github.com/user-attachments/assets/8310d1d1-c62c-47e2-854b-997827e4de5f)
![Katy Goford](https://github.com/user-attachments/assets/05da1445-0046-44b2-8615-68bf4317f438)
![Wendy Jackson](https://github.com/user-attachments/assets/5380dc08-0b7d-4118-add2-218cb0f0ee35)

**Comment by KateCourt** [comment]
Thanks Sue, I should be able to set this up for you and let you know where you can edit it. We're happy to keep supporting small additions to the site, but it might take me a while to get to them sometimes as we'd be doing this work for free. Larger changes would need further funding. I'll try and do this today or before the end of the week if possible!

**Comment by Thompsonse** [comment]
Yes totally understand Kate, and I really appreciate your support with these edits.

**Comment by KateCourt** [comment]
Thanks! You should be able to add the images and details now. 

If you add images to 'assets/images/nurses' and the information to '_data/nurses.yml' in the same way as you have with other sections it should work! Let me know how you get on.

**Comment by Thompsonse** [comment]
I've tried resizing the images however they seem to be out of align still, any suggestions please??

**Comment by KateCourt** [comment]
Looks like they're different rations of width to height?

**Comment by Thompsonse** [comment]
Ok I'll try again to resize them
